openapi: 3.0.0
info:
  version: 1.0.0
  x-go-package: "github.com/oapi-codegen/runtime"
  title: Sensor Data API
  license:
    name: MIT
  x-oapi-codegen-middlewares:
    - Middleware
servers:
  - url: http://localhost
paths:
  /api/v1.0/sensor-data:
    post:
      summary: Add Sensor Data
      operationId: addSensorData
      requestBody:
        description: Sensor data to add to the database
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorData'
      responses:
        '200':
          description: Sensor data added successfully
        '400':
          description: Bad request - Invalid input data
        '500':
          description: Internal Server Error

components:
  schemas:
    SensorData:
      type: object
      properties:
        SensorID:
          type: integer
        Value:
          type: number
        Timestamp:
          type: string
          format: date-time