openapi: 3.0.0
info:
  title: Sensor Data API
  version: 1.0.0
components:
  schemas:
    SensorData:
      type: object
      properties:
        SensorID:
          type: integer
        Value:
          type: number
        Timestamp:
          type: string
          format: date-time

paths:
  /sensor-data:
    post:
      summary: Add Sensor Data
      operationId: addSensorData
      requestBody:
        description: Sensor data to add to the database
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorData'
      responses:
        '201':
          description: Sensor data added successfully
        '400':
          description: Bad request - Invalid input data
        '500':
          description: Internal Server Error
